#!/usr/bin/env python3
"""Resolve a list of raw company names into scrapeable ATS boards.

WHY THIS EXISTS
---------------
A company list is usually just names + careers-page links (LinkedIn searches,
`acme.com/careers`, ...). None of that is machine-readable. This scraper needs
an (ats, slug) pair — the stable JSON endpoint behind the careers page.

This script closes that gap ONCE, offline, so the 4x-daily run stays fast:

  raw names  ──►  candidate slugs  ──►  probe 4 ATS APIs  ──►  confirmed boards
                  (name normalizing)     (live, non-empty)      → companies.yaml

The probing itself lives in src/discovery.py, shared with the in-run
self-healer (src/healer.py) so both agree on what "a real board" means.

Expect roughly 1 in 5 names to resolve. That is not a bug: most companies
aren't on a public-API ATS at all. Everything that misses is written to the
--unresolved CSV with a reason, so nothing disappears quietly.

Usage:
    python scripts/discover_ats.py --input companies.json \
        --out discovered.yaml --unresolved unresolved.csv [--deep] [--limit N]

Then fold the result in without clobbering curated entries:
    python scripts/merge_companies.py --curated config/companies.yaml \
        --discovered discovered.yaml --out config/companies.yaml
"""
from __future__ import annotations

import argparse
import csv
import json
import sys
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from src.discovery import find_board, probe_careers_page  # noqa: E402

WORKERS = 14


def resolve(company: dict, deep: bool) -> dict:
    """Find a scrapeable board for one company. Never raises."""
    name = company["company"]
    result = {"name": name, "status": "unresolved", "meta": company}
    careers = company.get("career_portal_url", "") if deep else ""
    try:
        found = find_board(name, careers_url=careers)
    except Exception:                        # noqa: BLE001 — a dead probe is a miss
        found = None
    if found:
        result.update(status="resolved", **found)
    return result


def _reject_bad_hits(hits: list[dict]) -> tuple[list[dict], list[dict]]:
    """Drop the two failure modes slug-guessing produces.

    1. Empty boards. A slug that resolves but serves 0 jobs is either stale or
       was never that company's board; either way it can only add noise.
    2. Slug collisions. "Apollo Hospitals" and "Apollo Diagnostics" both guess
       `apollo`, which on Greenhouse is Apollo GraphQL. When several distinct
       companies land on one board, at most one is right and we can't tell
       which — so none of them are trustworthy.
    """
    by_board: dict[tuple[str, str], list[dict]] = {}
    for r in hits:
        key = (r["ats"], str(r.get("slug") or r.get("workday_host", "")).lower())
        by_board.setdefault(key, []).append(r)

    keep, drop = [], []
    for key, group in by_board.items():
        if len(group) > 1:
            for r in group:
                r["status"] = f"rejected: slug collision on {key[0]}/{key[1]}"
                drop.append(r)
            continue
        r = group[0]
        if r.get("postings", 0) == 0:
            r["status"] = "rejected: board resolved but serves 0 postings"
            drop.append(r)
        else:
            keep.append(r)
    return keep, drop


def _fit_tier(meta: dict) -> str:
    """Map the source list's fit language to a priority tier used for ranking."""
    fit = (meta.get("profile_fit") or "").lower()
    for tier in ("high", "medium", "low"):
        if fit.startswith(tier):
            return tier
    return "unknown"


def _to_yaml(rows: list[dict]) -> str:
    out = [
        "# AUTO-GENERATED by scripts/discover_ats.py — every entry below was",
        "# confirmed live against its ATS API at generation time.",
        "# Merge with scripts/merge_companies.py; do not paste over a curated file.",
        "",
        "companies:",
    ]
    for r in rows:
        out.append(f"  - name: {json.dumps(r['name'])}")
        out.append(f"    ats: {r['ats']}")
        out.append(f"    slug: {json.dumps(str(r.get('slug', '')))}")
        if r["ats"] == "workday":
            out.append(f"    workday_host: {r.get('workday_host', '')}")
            out.append(f"    workday_path: {r.get('workday_path', '')}")
        out.append(f"    priority: {_fit_tier(r['meta'])}")
    return "\n".join(out) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--input", required=True, help="Company JSON (list under 'companies')")
    ap.add_argument("--out", default=None, help="Write YAML here (default: stdout preview)")
    ap.add_argument("--unresolved", default=None, help="CSV audit trail of misses")
    ap.add_argument("--limit", type=int, default=0, help="Only probe the first N (sampling)")
    ap.add_argument("--deep", action="store_true",
                    help="Also fetch careers pages — slower, but the only way to find Workday")
    args = ap.parse_args()

    raw = json.loads(Path(args.input).read_text(encoding="utf-8"))
    companies = raw["companies"] if isinstance(raw, dict) else raw
    if args.limit:
        companies = companies[: args.limit]

    print(f"Probing {len(companies)} companies (deep={args.deep}) ...", file=sys.stderr)
    started = time.time()
    results: list[dict] = []
    with ThreadPoolExecutor(max_workers=WORKERS) as pool:
        futs = [pool.submit(resolve, c, args.deep) for c in companies]
        for i, fut in enumerate(as_completed(futs), 1):
            r = fut.result()
            results.append(r)
            if r["status"] == "resolved":
                print(f"  HIT  {r['name'][:34]:<34} {r['ats']}/"
                      f"{r.get('slug') or r.get('workday_host')} ({r['postings']} postings)",
                      file=sys.stderr)
            if i % 100 == 0:
                hits = sum(1 for x in results if x["status"] == "resolved")
                print(f"  ... {i}/{len(companies)} probed, {hits} resolved "
                      f"({time.time() - started:.0f}s)", file=sys.stderr)

    hits = [r for r in results if r["status"] == "resolved"]
    miss = [r for r in results if r["status"] != "resolved"]
    print(f"\nResolved {len(hits)}/{len(results)} "
          f"({100 * len(hits) / max(len(results), 1):.1f}%) in {time.time() - started:.0f}s",
          file=sys.stderr)

    hits, rejected = _reject_bad_hits(hits)
    miss.extend(rejected)
    print(f"After collision/empty filtering: {len(hits)} usable, {len(rejected)} rejected",
          file=sys.stderr)

    hits.sort(key=lambda r: r["name"].lower())
    if args.out:
        Path(args.out).write_text(_to_yaml(hits), encoding="utf-8")
        print(f"Wrote {args.out}", file=sys.stderr)
    else:
        print(_to_yaml(hits[:25]))

    if args.unresolved:
        with open(args.unresolved, "w", newline="", encoding="utf-8") as fh:
            w = csv.writer(fh)
            w.writerow(["company", "why", "career_portal_url", "sector", "profile_fit"])
            for r in sorted(miss, key=lambda x: x["name"].lower()):
                m = r["meta"]
                w.writerow([r["name"], r["status"], m.get("career_portal_url", ""),
                            m.get("sector", ""), m.get("profile_fit", "")])
        print(f"Wrote {args.unresolved} ({len(miss)} unresolved)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
